import { StyleSheet } from "react-native";
import { Colors } from "./theme";

export const GS = StyleSheet.create({
    card: {
        backgroundColor: Colors.white,
        borderRadius: 12,
        padding: 16,
        marginVertical: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: "bold",
        marginBottom: 8,
        color: Colors.text,
    },
    cardText: {
        fontSize: 14,
        color: Colors.textSecondary,
    },
    m8: { margin: 8 },
    m16: { margin: 16 },
    mx8: { marginHorizontal: 8 },
    mx16: { marginHorizontal: 16 },
    my8: { marginVertical: 8 },
    my16: { marginVertical: 16 },
    p8: { padding: 8 },
    p16: { padding: 16 },
    px8: { paddingHorizontal: 8 },
    px16: { paddingHorizontal: 16 },
    py8: { paddingVertical: 8 },
    py16: { paddingVertical: 16 },
    ml8: { marginLeft: 8 },
    mr8: { marginRight: 8 },
    mt8: { marginTop: 8 },
    mb8: { marginBottom: 8 },
    pt8: { paddingTop: 8 },
    pb8: { paddingBottom: 8 },
    pl8: { paddingLeft: 8 },
    pr8: { paddingRight: 8 },
    border: { borderWidth: 1, borderColor: "#ccc" },
    border2: { borderWidth: 2, borderColor: "#ccc" },
    rounded: { borderRadius: 4 },
    roundedLg: { borderRadius: 8 },
    roundedXl: { borderRadius: 16 },
    bgWhite: { backgroundColor: "#fff" },
    bgGray: { backgroundColor: "#f5f5f5" },
    bgBlue: { backgroundColor: "#3b82f6" },
});
